# Generated by Django 5.0.2 on 2024-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/advertisement/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/advertisement/'),
        ),
    ]
