# Generated by Django 5.0.1 on 2024-02-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_name_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/upload_image/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
