# Generated by Django 5.0.2 on 2024-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image_alter_blog_video'),
        ('user', '0005_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to='user.customer'),
        ),
    ]
