# Generated by Django 5.0.1 on 2024-02-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(upload_to='images/user_image/'),
        ),
    ]
