# Generated by Django 5.0.1 on 2024-02-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customer_email_remove_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
