# Generated by Django 5.0.2 on 2024-04-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
