# Generated by Django 5.0.2 on 2024-04-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createvideo',
            name='video',
            field=models.FileField(null=True, upload_to='video/short-video/'),
        ),
    ]
